version: '3.8'

services:
  ai-job-autopilot:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: ai-job-autopilot-prod
    restart: unless-stopped
    
    ports:
      - "8501:8501"
    
    environment:
      # AI API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      
      # Platform Credentials
      - LINKEDIN_EMAIL=${LINKEDIN_EMAIL}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}
      - INDEED_EMAIL=${INDEED_EMAIL}
      - INDEED_PASSWORD=${INDEED_PASSWORD}
      - NAUKRI_EMAIL=${NAUKRI_EMAIL}
      - NAUKRI_PASSWORD=${NAUKRI_PASSWORD}
      
      # Application Settings
      - CANDIDATE_NAME=Ankit Thakur
      - CANDIDATE_EMAIL=${CANDIDATE_EMAIL}
      - CANDIDATE_PHONE=${CANDIDATE_PHONE}
      - CANDIDATE_LOCATION=Bangalore, India
      
      # Security
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SESSION_TIMEOUT=3600
      
      # Performance
      - MAX_APPLICATIONS_PER_DAY=20
      - REQUEST_DELAY_SECONDS=5
      - LOG_LEVEL=INFO
      
      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_HEADLESS=true
    
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./uploads:/app/uploads
      - ./data:/app/data
    
    networks:
      - ai-job-autopilot-network
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-job-autopilot.rule=Host(`job-autopilot.ankitthakur.dev`)"
      - "traefik.http.routers.ai-job-autopilot.tls=true"
      - "traefik.http.routers.ai-job-autopilot.tls.certresolver=letsencrypt"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session management
  redis:
    image: redis:7-alpine
    container_name: ai-job-autopilot-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ai-job-autopilot-network

  # Optional: PostgreSQL for data persistence
  postgres:
    image: postgres:15-alpine
    container_name: ai-job-autopilot-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ai_job_autopilot
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai-job-autopilot-network

networks:
  ai-job-autopilot-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data: