# AI Job Autopilot - Credentials Configuration
# For Ankit Thakur's Profile
# 
# SECURITY NOTE: Never commit actual passwords to version control
# Set environment variables or use secure credential management

# Personal Information
profile:
  name: "Ankit Thakur"
  email: "ankit.thakur@gmail.com"
  phone: "+91 98765 43210"
  location: "Bangalore, India"
  linkedin: "linkedin.com/in/ankitthakur"
  github: "github.com/ankitthakur"

# Platform Credentials (Fill in actual values)
platforms:
  linkedin:
    email: "ankit.thakur@gmail.com"
    password: ""  # Set via environment variable LINKEDIN_PASSWORD
    
  indeed:
    email: "ankit.thakur@gmail.com" 
    password: ""  # Set via environment variable INDEED_PASSWORD
    
  naukri:
    email: "ankit.thakur@gmail.com"
    password: ""  # Set via environment variable NAUKRI_PASSWORD

# AI API Keys (Set via environment variables)
ai_services:
  openai_api_key: ""      # Set via OPENAI_API_KEY
  anthropic_api_key: ""   # Set via ANTHROPIC_API_KEY
  google_api_key: ""      # Set via GOOGLE_API_KEY

# Job Preferences  
job_preferences:
  titles:
    - "Senior Software Engineer"
    - "Full Stack Developer"
    - "Backend Engineer" 
    - "Python Developer"
    - "Tech Lead"
    - "Software Architect"
  
  locations:
    - "Remote"
    - "Bangalore, India"
    - "Hyderabad, India"
    - "Pune, India"
    - "Chennai, India"
    - "Mumbai, India"
  
  salary:
    min_inr: 1500000  # 15 LPA
    max_inr: 3500000  # 35 LPA  
    min_usd: 80000    # For international roles
    max_usd: 150000
  
  preferences:
    job_type: "Full-time"
    remote_preferred: true
    company_size: ["Startup", "Mid-size", "Large"] 
    industries: ["Technology", "FinTech", "E-commerce", "SaaS"]

# Application Settings
automation:
  max_applications_per_day: 20
  delay_between_applications: 
    min_seconds: 30
    max_seconds: 120
  
  filters:
    skip_companies: []  # Companies to avoid
    required_keywords: ["python", "backend", "api"]
    
  responses:
    auto_answer_questions: true
    generate_cover_letters: true
    customize_for_role: true

# Notification Settings  
notifications:
  email: "ankit.thakur@gmail.com"
  send_daily_summary: true
  send_application_updates: true
  send_response_alerts: true

# Resume Information
resume:
  experience_years: 5.5
  current_role: "Senior Software Engineer"
  current_company: "TechCorp India"
  key_skills:
    - "Python"
    - "JavaScript"
    - "React"
    - "Django"
    - "AWS"
    - "PostgreSQL"
    - "Docker"
    - "Kubernetes"
  
  achievements:
    - "Led development of microservices architecture"
    - "Improved system performance by 40%"
    - "Mentored 3 junior developers"
    - "Delivered 15+ production features"

# Instructions for setup:
# 1. Copy this file to config/credentials.yaml
# 2. Set environment variables for sensitive data:
#    export LINKEDIN_PASSWORD="your_password"
#    export INDEED_PASSWORD="your_password" 
#    export OPENAI_API_KEY="your_api_key"
# 3. Never commit actual passwords to git
# 4. Use .env file for local development