name: "Ankit Thakur"
email: "at87.at17@gmail.com"
phone: "+91 8717934430"
location: "Remote / Europe"

skills:
  - cybersecurity
  - penetration testing
  - vulnerability assessment
  - cloud security
  - aws
  - network security
  - incident response
  - compliance
  - risk assessment
  - security architecture
  - python
  - javascript
  - sql
  - linux
  - docker
  - kubernetes
  - terraform

experience_level: "senior"
total_experience_years: 5.5

preferred_locations:
  - "Remote"
  - "Berlin"
  - "Munich" 
  - "Hamburg"
  - "London"
  - "Amsterdam"
  - "Dublin"

job_types:
  - "full-time"
  - "contract"

salary_expectations:
  min: 80000
  max: 150000
  currency: "EUR"

work_authorization: "EU Citizen"
visa_sponsorship_required: false

industries:
  - "Technology"
  - "Financial Services"
  - "Cybersecurity"
  - "Cloud Computing"
  - "Fintech"

company_sizes:
  - "Startup"
  - "Medium"
  - "Large"

availability: "Two weeks notice"

keywords:
  - "security engineer"
  - "cybersecurity engineer"
  - "cloud security engineer"
  - "application security engineer"
  - "security architect"
  - "penetration tester"
  - "security analyst"
  - "information security"